import {
  ApplicationConfig,
  LOCALE_ID,
  inject,
  provideAppInitializer,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideIcons } from '@ng-icons/core';
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';
import { SessionService } from '@core/services/session.service';
import {
  lucideLayoutDashboard,
  lucideCalendar,
  lucideCalendarCheck,
  lucidePhone,
  lucidePhoneCall,
  lucideUsers,
  lucideUtensilsCrossed,
  lucideSettings,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronDown,
  lucideChevronUp,
  lucideSearch,
  lucideBell,
  lucideCheck,
  lucideCircleCheck,
  lucideX,
  lucidePlus,
  lucideEllipsis,
  lucideLogOut,
  lucideGrid2x2,
  lucideStore,
  lucideChartColumn,
  lucideMenu,
  lucideInfo,
  lucideUnlink,
  lucideList,
  lucideLayoutGrid,
  lucidePencil,
  lucideUndo2,
  lucideRedo2,
  lucideRows3,
  lucideCopy,
  lucideTrash2,
  lucideAlignHorizontalJustifyCenter,
  lucideDownload,
  lucideMaximize,
  lucideUpload,
  lucideBox,
  lucideSave,
  lucideLeaf,
  lucideWrench,
  lucideCreditCard,
  lucideRefreshCw,
  lucideMinus,
  lucideFileText,
} from '@ng-icons/lucide';

import { routes } from './app.routes';

registerLocaleData(localeFr);

// Icônes Lucide utilisées dans l'app, enregistrées une fois pour toutes.
const ICONS = {
  lucideLayoutDashboard,
  lucideCalendar,
  lucideCalendarCheck,
  lucidePhone,
  lucidePhoneCall,
  lucideUsers,
  lucideUtensilsCrossed,
  lucideSettings,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronDown,
  lucideChevronUp,
  lucideSearch,
  lucideBell,
  lucideCheck,
  lucideCircleCheck,
  lucideX,
  lucidePlus,
  lucideEllipsis,
  lucideLogOut,
  lucideGrid2x2,
  lucideStore,
  lucideChartColumn,
  lucideMenu,
  lucideInfo,
  lucideUnlink,
  lucideList,
  lucideLayoutGrid,
  lucidePencil,
  lucideUndo2,
  lucideRedo2,
  lucideRows3,
  lucideCopy,
  lucideTrash2,
  lucideAlignHorizontalJustifyCenter,
  lucideDownload,
  lucideMaximize,
  lucideUpload,
  lucideBox,
  lucideSave,
  lucideLeaf,
  lucideWrench,
  lucideCreditCard,
  lucideRefreshCw,
  lucideMinus,
  lucideFileText,
};

export const appConfig: ApplicationConfig = {
  providers: [
    { provide: LOCALE_ID, useValue: 'fr' },
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(withFetch()),
    provideIcons(ICONS),
    provideAppInitializer(() => inject(SessionService).refresh()),
  ],
};
